name: Run tests

on: 
  workflow_dispatch:
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno Test
        run: deno task test

      - name: Build JSR
        run: deno task build-jsr

      - name: Build NPM
        run: deno task build-npm